# used to integrate with github actions
name: ci 
on:
  push:
    branches: # listens for pushes to master and main branches
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      # Install dependencies       
      - run: pip install mkdocs-material
      # Build and deploy   
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
